### ISSUE TITLE
Permalien vers un résultat

### ISSUE THREAD

**Issue by johanricher** [glae/garelaplusproche.fr#24]
En tant qu'utilisateur j'aimerais bien pouvoir partager un lien vers un résultat trouvé sur garelaplusproche.fr afin de montrer à quelqu'un la gare la plus proche de la commune d'arrivée d'un trajet.

**Comment by glae** [comment]
@johanricher Bonjour, désolé pour le délai (plus d'un an...), j'ai dû passer à côté de la notification. 
C'est désormais en place : 
- exemple de lien : https://www.garelaplusproche.fr/?lat=44.3912906&long=0.904969
- bouton : ![image](https://github.com/glae/lagarelaplusproche.fr/assets/1540636/1788c73b-8499-4ead-b9ef-474c64fafe35)

N'hésitez à pas me faire votre retour.

**Comment by johanricher** [comment]
J'avais en effet complètement oublié avoir ouvert cette issue. :smile: Merci beaucoup d'avoir ajouté cette fonctionnalité qui répond entièrement à mon besoin et qui rend le site encore plus utile ! Je vous en suis très reconnaissant et vous dis bravo pour ce site très pratique et ingénieux qui mérite d'être plus connu. :clap:

**Comment by gaelmercier** [comment]
Merci pour votre retour !
