### ISSUE TITLE
Amélioration de la recherche par commune

### ISSUE THREAD

**Issue by johanricher** [glae/garelaplusproche.fr#30]
Sur [la page d'accueil](https://www.garelaplusproche.fr/), après avoir trouvé une commune il faut cliquer sur le bouton situé au-dessus du champ de recherche pour finaliser la recherche et localiser la commune sur la carte. Ce comportement ne me semble pas très intuitif et peut échapper à certaines personnes. Il m'a ainsi fallu relire le texte pour comprendre le fonctionnement.

Serait-il possible de déclencher la localisation de la commune sur la carte lorsqu'un on en choisit dans le menu et/ou après avoir appuyé sur la touche Entrée ?

Merci encore pour votre travail et ce projet !

**Comment by glae** [comment]
Effectivement ce comportement, ajouté sur le tard, n'est pas intuitif. Vos propositions sont pertinentes, je vais regarder. Je me rends compte aussi que le premier texte n'est pas toujours bon (voir #33).

**Comment by glae** [comment]
@johanricher c'est fait : https://www.garelaplusproche.fr/

**Comment by johanricher** [comment]
C'est parfait, merci !
